### ISSUE TITLE
Setting should be on a per-tab basis

### ISSUE THREAD

**Issue by ctrlcctrlv** [M-Reimer/togglefonts#2]
Seems weird that when I enable/disable fonts all fonts on all tabs are set that way

**Comment by M-Reimer** [comment]
It is not possible to limit this as the API feature, that I use, is a global setting.

**Comment by ctrlcctrlv** [comment]
@M-Reimer Hi, just wondering if it's not possible to use another API? It might be slow to go element-by-element, but perhaps you could look up the user's preferred fonts, then if an element isn't using one of those, switch to it. Just an idea. :-)

**Comment by M-Reimer** [comment]
No this is not possible as you won't catch all cases.

Best solution is (in my opinion) if you use an ad blocker addon to block font URLs you don't like. For example I have the "Google web fonts" blacklisted in uBlock
