### ISSUE TITLE
question about privacy

### ISSUE THREAD

**Issue by atomGit** [M-Reimer/togglefonts#4]
from what i can tell the extension only toggles the font styles (like it says on the tin) but does not prevent requests to the domains hosting the fonts - i understand this and this is ok, but my question is whether it prevents downloading of 3rd party fonts

**Comment by ctrlcctrlv** [comment]
This extension toggles the global `gfx.downloadable_fonts.enabled` setting, so it does prevent downloading of third party fonts when turned on, yes.

**Comment by atomGit** [comment]
great, thanks

**Comment by atomGit** [comment]
> This extension toggles the global gfx.downloadable_fonts.enabled 

actually it doesn't - it toggles `browser.display.use_document_fonts` only

it would perhaps be nice if it toggled both, though maybe a page refresh would be necessary

**Comment by M-Reimer** [comment]
You may be right here. The font file itself is still downloaded as far as I can tell with the developer tools.

> it would perhaps be nice if it toggled both, though maybe a page refresh would be necessary

Impossible. I don't toggle any preference (as this is not possible for Addons) but use the API provided by Mozilla: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/useDocumentFonts

I could try to file this as bug against the API in hope Mozilla decides to toggle both settings.

Or I could **in parallel** to toggling the above setting also set up a content filter to deny font file downloading.

But to be honest I think this is more a job for an Ad blocker. If you, for example, don't like to download "Google Web Fonts", then just add this filter:

    ||fonts.gstatic.com
    ||fonts.googleapis.com

I have them on all my systems. Everywhere the "Google fonts" look good, my system fonts just work as well.

**Comment by atomGit** [comment]
i already block 3rd party fonts with uBlock and yeah, i guess you're right; better task for a blocker

this is what i'm using in uBlock -> My Filters if anyone is curious - this, i think, avoids the CSP issue, or at least one of them:

```
! fonts: the following line will allow 1st party fonts globally while blocking all 3rd party fonts:
! *$font,third-party
*$font,third-party,domain=~gitlab.com
! to allow 3rd party fonts per domain:
! *$font,third-party,domain=~example.com
! to allow 3rd party fonts for additional domains:
! *$font,third-party,domain=~example.com|~example2.com
```
