### ISSUE TITLE
On or off

### ISSUE THREAD

**Issue by arnauldb** [M-Reimer/togglefonts#5]
Hello,
can you tell me when it is on or off. ..with the cross or not?
Thank you

**Comment by M-Reimer** [comment]
**Fonts** are off if the cross is visible. All my "toggle Add-ons" work this way with one exception: "Toggle Referrers". There I wanted to clearly see when I send the Referrer so it has a red exclamation mark if Referrers are on.

The whole Add-on is about toggling fonts. You don't disable the Add-on (which is only possible in about:addons anyway) but you disable fonts.

You can also keep your mouse over the icon for some time and the tooltip should tell you.

**Comment by arnauldb** [comment]
> **Fonts** are off if the cross is visible.

So, when the cross is visible, remote fonts are disabled and local fonts on my computer are enabled? Sorry to insist but it is not that clear for me.
Thank you.

**Comment by M-Reimer** [comment]
If the cross is not visible, then simply "everything" is allowed. Not every website defines own fonts so "local fonts" will be used there always.

My short description on AMO describes what the Add-on does:
> Disables or enables the use of fonts specified by the web page.

And this is the Mozilla description of the setting that is changed if you click the icon:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/useDocumentFonts

    true (no cross): use the fonts specified by the web page. This is the default.
    false (cross):  use the system fonts.
